CREATE TABLE IF NOT EXISTS Users (
    ID SERIAL PRIMARY KEY,
    Name VARCHAR(100) NOT NULL
);
CREATE TABLE IF NOT EXISTS UserPreferences (
    id SERIAL PRIMARY KEY,
    UserId INT,
    description VARCHAR(255),
    FOREIGN KEY (UserId) REFERENCES Users(id) ON DELETE CASCADE
);
CREATE TABLE students (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100)
);
CREATE OR REPLACE PROCEDURE add_student(student_name VARCHAR) LANGUAGE plpgsql AS $$ BEGIN
INSERT INTO students(name)
VALUES(student_name);
END;
$$;