CREATE TABLE IF NOT EXISTS Users (
    ID SERIAL PRIMARY KEY,
    Name VARCHAR(100) NOT NULL
);
CREATE TABLE IF NOT EXISTS UserPreferences (
    id SERIAL PRIMARY KEY,
    UserId INT,
    description VARCHAR(255),
    FOREIGN KEY (UserId) REFERENCES Users(id) ON DELETE CASCADE
);